version: '3.8'

services:
  # Core Services
  orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator/Dockerfile
    container_name: autocontentor_orchestrator
    restart: unless-stopped
    environment:
      - APP_ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    networks:
      - autocontentor_network
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Agent Services
  keyword-agent:
    build:
      context: .
      dockerfile: docker/agents/keyword/Dockerfile
    container_name: autocontentor_keyword_agent
    restart: unless-stopped
    environment:
      - APP_ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - KEYWORD_AGENT_PORT=8001
    ports:
      - "8001:8001"
    networks:
      - autocontentor_network
    volumes:
      - ./logs:/app/logs

  audience-agent:
    build:
      context: .
      dockerfile: docker/agents/audience/Dockerfile
    container_name: autocontentor_audience_agent
    restart: unless-stopped
    environment:
      - APP_ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - AUDIENCE_AGENT_PORT=8002
    ports:
      - "8002:8002"
    networks:
      - autocontentor_network
    volumes:
      - ./logs:/app/logs

  competitor-agent:
    build:
      context: .
      dockerfile: docker/agents/competitor/Dockerfile
    container_name: autocontentor_competitor_agent
    restart: unless-stopped
    environment:
      - APP_ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - COMPETITOR_AGENT_PORT=8003
    ports:
      - "8003:8003"
    networks:
      - autocontentor_network
    volumes:
      - ./logs:/app/logs

  trend-agent:
    build:
      context: .
      dockerfile: docker/agents/trend/Dockerfile
    container_name: autocontentor_trend_agent
    restart: unless-stopped
    environment:
      - APP_ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - TREND_AGENT_PORT=8004
    ports:
      - "8004:8004"
    networks:
      - autocontentor_network
    volumes:
      - ./logs:/app/logs

  aggregator-agent:
    build:
      context: .
      dockerfile: docker/agents/aggregator/Dockerfile
    container_name: autocontentor_aggregator_agent
    restart: unless-stopped
    environment:
      - APP_ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - AGGREGATOR_AGENT_PORT=8005
    ports:
      - "8005:8005"
    networks:
      - autocontentor_network
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports

networks:
  autocontentor_network:
    driver: bridge
